# Forge-Nachrichtenkatalog: Deutsch (de)
# Wird beim Start von /usr/bin/forge eingelesen. Fuellt FORGE_MSG mit
# Schluesseln, die mit "de:" beginnen. Vorlagen verwenden printf-Platzhalter
# %s/%d, die von der Funktion msg() im Hauptskript positionell ersetzt werden.

FORGE_MSG[de:smith_usage]="Error: Gib das zu smithende Paket an, z. B. 'forge smith foo'"
FORGE_MSG[de:lock_exists]="Error: Es existiert bereits eine Lock-Datei unter /var/lock/forge.lock, vermutlich von einer laufenden forge-Operation; falls nicht, entferne die Lock-Datei und versuche es erneut."
FORGE_MSG[de:recipe_not_found]="Error: Rezept fur '%s' wurde in %s nicht gefunden"
FORGE_MSG[de:dry_run_start]="Prufe (Dry Run) das Paket %s..."
FORGE_MSG[de:smith_start]="Smithing des Pakets: %s..."
FORGE_MSG[de:checksum_fetch_attempt]="Keine lokale Prufsumme fur '%s' gefunden; versuche, sie von CHECKSUM_URL abzurufen..."
FORGE_MSG[de:missing_deps]="Error: '%s' hangt von noch nicht installierten Paket(en) ab: %s"
FORGE_MSG[de:missing_deps_hint]="Fuhre 'forge smith <Paket>' zuerst fur jedes davon aus und versuche es dann erneut."
FORGE_MSG[de:dry_run_header]="=== Dry Run: forge smith %s ==="
FORGE_MSG[de:dry_run_name]="Name: %s"
FORGE_MSG[de:dry_run_version]="Version: %s"
FORGE_MSG[de:dry_run_url]="URL: %s"
FORGE_MSG[de:dry_run_checksum_sha256]="Prufsumme: SHA256SUM definiert, wurde geprueft werden"
FORGE_MSG[de:dry_run_checksum_md5]="Prufsumme: MD5SUM definiert, wurde geprueft werden"
FORGE_MSG[de:dry_run_checksum_none]="Prufsumme: keine definiert, Prufung wurde uebersprungen werden"
FORGE_MSG[de:dry_run_deps]="Abhangigkeiten: %s (alle erfullt)"
FORGE_MSG[de:dry_run_action_already_installed]="Aktion: Paket ist bereits in dieser Version installiert; ein echter Lauf wurde nach Neuinstallation fragen (oder mit -y/--yes nichts tun, mit -f/--force erzwingen)"
FORGE_MSG[de:dry_run_action_upgrade]="Aktion: wurde von %s auf %s aktualisieren"
FORGE_MSG[de:dry_run_action_fresh]="Aktion: wurde eine Neuinstallation durchfuhren"
FORGE_MSG[de:dry_run_cached_tarball]="Hinweis: Ein zwischengespeichertes Tarball existiert bereits unter %s und wurde wiederverwendet werden, falls die Prufsumme uebereinstimmt"
FORGE_MSG[de:dry_run_footer]="Es wurden keine Dateien heruntergeladen, gebaut oder installiert (Dry Run)."
FORGE_MSG[de:resume_found]="Unvollstandiger Build von %s in %s gefunden -- wird an der Stelle fortgesetzt, an der er unterbrochen wurde."
FORGE_MSG[de:resume_hint]="(mit 'forge smith %s --clean' verwerfen und von vorn beginnen)"
FORGE_MSG[de:archive_unrecognized]="Error: Archivformat von '%s' nicht erkannt (unterstutzt: .tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip)."
FORGE_MSG[de:interrupted]="Unterbrochen! Der Fortschritt in %s wurde beibehalten."
FORGE_MSG[de:interrupted_hint]="Fuhre 'forge smith %s' erneut aus, um dort fortzufahren, oder verwende --clean, um neu zu beginnen."
FORGE_MSG[de:already_installed]="Paket '%s' ist bereits in Version %s installiert."
FORGE_MSG[de:forcing_reinstall]="Erzwinge Neuinstallation (-f|--force)."
FORGE_MSG[de:nothing_to_do]="Nichts zu tun."
FORGE_MSG[de:prompt_reinstall]="Trotzdem neu installieren? [y/N] "
FORGE_MSG[de:reinstall_aborted]="Neuinstallation abgebrochen."
FORGE_MSG[de:currently_installed_upgrading]="Paket '%s' ist derzeit in Version %s installiert, Aktualisierung auf %s."
FORGE_MSG[de:prompt_upgrade]="Mit Aktualisierung auf %s fortfahren? [y/N] "
FORGE_MSG[de:upgrade_aborted]="Aktualisierung abgebrochen."
FORGE_MSG[de:not_installed]="Paket '%s' ist derzeit nicht installiert."
FORGE_MSG[de:prompt_smith]="Mit Smithing von '%s' %s fortfahren? [y/N] "
FORGE_MSG[de:smith_aborted]="Smithing abgebrochen."
FORGE_MSG[de:skip_download_resume]="Download und Extraktion werden uebersprungen (bestehender Build wird fortgesetzt)."
FORGE_MSG[de:cached_tarball]="Gultiges zwischengespeichertes Tarball unter %s gefunden, Download wird uebersprungen."
FORGE_MSG[de:downloading]="Get:%s %s"
FORGE_MSG[de:download_failed]="Download von %s von %s fehlgeschlagen"
FORGE_MSG[de:download_empty]="Heruntergeladene Datei %s fehlt oder ist leer."
FORGE_MSG[de:download_empty_hint]="Prufe deine Internetverbindung. Falls das nicht das Problem ist, wurde der Download moglicherweise auf eine Fehlerseite umgeleitet, oder die URL/VERSION im Rezept ist falsch."
FORGE_MSG[de:verifying_checksum]="Prufsumme wird verifiziert (%s)..."
FORGE_MSG[de:checksum_compute_failed]="Prufsumme fur %s konnte nicht berechnet werden (Datei nicht lesbar oder %s fehlgeschlagen)."
FORGE_MSG[de:checksum_mismatch]="Prufsumme stimmt nicht uberein fur %s!"
FORGE_MSG[de:checksum_expected]="	Erwartet: %s"
FORGE_MSG[de:checksum_got]="	Erhalten: %s"
FORGE_MSG[de:checksum_kept]="Tarball zur Untersuchung unter %s aufbewahrt."
FORGE_MSG[de:checksum_ok]="Prufsumme OK"
FORGE_MSG[de:no_checksum_warning]="Keine SHA256SUM oder MD5SUM im Rezept fur %s definiert, Prufung wird uebersprungen..."
FORGE_MSG[de:extract_failed]="Extraktion von %s fehlgeschlagen"
FORGE_MSG[de:mold_skip]="mold() wurde bereits bei einem fruheren Versuch abgeschlossen -- springe direkt zu smith()."
FORGE_MSG[de:molding]="Molding (Build) lauft"
FORGE_MSG[de:mold_failed]="mold() fur %s fehlgeschlagen. Details siehe %s. Abbruch vor der Installation."
FORGE_MSG[de:smithing_isolated]="Smithing in isolierter Umgebung"
FORGE_MSG[de:smith_failed]="smith() fur %s fehlgeschlagen. Details siehe %s. Abbruch vor der Installation."
FORGE_MSG[de:generating_manifest]="Dateimanifest wird erstellt..."
FORGE_MSG[de:installing_files]="Dateien werden auf dem echten System installiert"
FORGE_MSG[de:running_finish]="Nachinstallationsschritte werden ausgefuhrt (finish())..."
FORGE_MSG[de:finish_warning]="finish() hat einen Fehler gemeldet. Prufe die Ausgabe oben; das Paket selbst ist weiterhin installiert."
FORGE_MSG[de:smithed_success]="Paket '%s-%s' erfolgreich smithed!"

# Neue Schluessel: Abhaengigkeitskaskade + Zusatzdateien
FORGE_MSG[de:circular_dep]="Zirkulaere Abhaengigkeit erkannt: %s"
FORGE_MSG[de:dep_recipe_not_found]="Rezept fuer Abhaengigkeit '%s' nicht gefunden (benoetigt von: %s)"
FORGE_MSG[de:plan_resolving]="Abhaengigkeiten fuer %s werden aufgeloest..."
FORGE_MSG[de:plan_header]="Die folgenden Pakete werden ebenfalls installiert:"
FORGE_MSG[de:plan_count]="%s neu zu installierende(s) Paket(e)."
FORGE_MSG[de:plan_confirm]="Fortfahren? [Y/n] "
FORGE_MSG[de:plan_aborted]="Abgebrochen."
FORGE_MSG[de:dep_cascade_failed]="Installation der Abhaengigkeit '%s' fehlgeschlagen. Abbruch -- '%s' wurde nicht installiert."
FORGE_MSG[de:extra_file_header]="Zusatzdateien (Patches usw.) fuer %s werden abgerufen..."
FORGE_MSG[de:extra_file_failed]="Abrufen einer Zusatzdatei fuer %s fehlgeschlagen. Abbruch vor dem Build."
