# Forge message catalog: English (en)
# Sourced by /usr/bin/forge at startup. Populates FORGE_MSG with keys
# prefixed "en:". Templates use printf %s/%d placeholders, substituted
# positionally by the msg() function in the main script.

FORGE_MSG[en:smith_usage]="Error: Specify the package to smith, e.g. 'forge smith foo'"
FORGE_MSG[en:lock_exists]="Error: existing lock file /var/lock/forge.lock, likely to be by an already existing forge operation, if there's not, remove the lock file and try again."
FORGE_MSG[en:recipe_not_found]="Error: Recipe for '%s' not found on %s"
FORGE_MSG[en:dry_run_start]="Assaying (dry run) the package %s..."
FORGE_MSG[en:smith_start]="Smithing the package: %s..."
FORGE_MSG[en:checksum_fetch_attempt]="No local checksum found for '%s'; attempting to fetch from CHECKSUM_URL..."
FORGE_MSG[en:missing_deps]="Error: '%s' depends on package(s) not yet installed: %s"
FORGE_MSG[en:missing_deps_hint]="Run 'forge smith <package>' for each one first, then retry."

FORGE_MSG[en:dry_run_header]="=== Dry run: forge smith %s ==="
FORGE_MSG[en:dry_run_name]="Name: %s"
FORGE_MSG[en:dry_run_version]="Version: %s"
FORGE_MSG[en:dry_run_url]="URL: %s"
FORGE_MSG[en:dry_run_checksum_sha256]="Checksum: SHA256SUM defined, would be verified"
FORGE_MSG[en:dry_run_checksum_md5]="Checksum: MD5SUM defined, would be verified"
FORGE_MSG[en:dry_run_checksum_none]="Checksum: none defined, verification would be skipped"
FORGE_MSG[en:dry_run_deps]="Dependencies: %s (all satisfied)"
FORGE_MSG[en:dry_run_action_already_installed]="Action: package already installed at this version; a real run would ask to reinstall (or no-op with -y/--yes, force with -f/--force)"
FORGE_MSG[en:dry_run_action_upgrade]="Action: would upgrade from %s to %s"
FORGE_MSG[en:dry_run_action_fresh]="Action: would perform a fresh install"
FORGE_MSG[en:dry_run_cached_tarball]="Note: a cached tarball already exists at %s and would be reused if its checksum matches"
FORGE_MSG[en:dry_run_footer]="No files were download, built, or installed (dry run)."

FORGE_MSG[en:resume_found]="Incomplete build of %s found at %s -- resuming where it left off."
FORGE_MSG[en:resume_hint]="(use 'forge smith %s --clean' to discard it and start over)"
FORGE_MSG[en:archive_unrecognized]="Error: couldn't recognize the archive format of '%s' (supported: .tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip)."
FORGE_MSG[en:interrupted]="Interrupted! Progress in %s was kept."
FORGE_MSG[en:interrupted_hint]="Run 'forge smith %s' again to resume where it left off, or use --clean to start over."

FORGE_MSG[en:already_installed]="Package '%s' is already installed at version %s."
FORGE_MSG[en:forcing_reinstall]="Forcing reinstall (-f|--force)."
FORGE_MSG[en:nothing_to_do]="Nothing to do."
FORGE_MSG[en:prompt_reinstall]="Reinstall it anyway? [y/N] "
FORGE_MSG[en:reinstall_aborted]="Reinstallation aborted."
FORGE_MSG[en:currently_installed_upgrading]="Package '%s' is currently installed at version %s, upgrading to %s."
FORGE_MSG[en:prompt_upgrade]="Proceed with upgrade to %s? [y/N] "
FORGE_MSG[en:upgrade_aborted]="Upgrade aborted."
FORGE_MSG[en:not_installed]="Package '%s' is not currently installed."
FORGE_MSG[en:prompt_smith]="Proceed with smithing '%s' %s? [y/N] "
FORGE_MSG[en:smith_aborted]="Smithing aborted."

FORGE_MSG[en:skip_download_resume]="Skipping download and extraction (resuming existing build)."
FORGE_MSG[en:cached_tarball]="Valid cached tarball found at %s, skipping download."
FORGE_MSG[en:downloading]="Get:%s %s"
FORGE_MSG[en:download_failed]="Failed to download %s from %s"
FORGE_MSG[en:download_empty]="Download file %s is missing or empty."
FORGE_MSG[en:download_empty_hint]="Check your internet connection. If that's not the issue, the download may have been redirected to an error page, or the URL/VERSION in the recipe, may be wrong."
FORGE_MSG[en:verifying_checksum]="Verifying checksum (%s)..."
FORGE_MSG[en:checksum_compute_failed]="Could not compute checksum for %s (file unreadable or %s failed)."
FORGE_MSG[en:checksum_mismatch]="Checksum mismatch for %s!"
FORGE_MSG[en:checksum_expected]="	Expected: %s"
FORGE_MSG[en:checksum_got]="	Got:	  %s"
FORGE_MSG[en:checksum_kept]="Tarball kept at %s for inspection."
FORGE_MSG[en:checksum_ok]="Checksum OK"
FORGE_MSG[en:no_checksum_warning]="No SHA256SUM or MD5SUM defined in recipe for %s, skipping verification..."
FORGE_MSG[en:extract_failed]="Failed to extract %s"

FORGE_MSG[en:mold_skip]="mold() already finished on a previous attempt -- skipping straight to smith()."
FORGE_MSG[en:molding]="Molding"
FORGE_MSG[en:mold_failed]="mold() failed for %s. See %s for details. Aborting before install."
FORGE_MSG[en:smithing_isolated]="Smithing in isolated environment"
FORGE_MSG[en:smith_failed]="smith() failed for %s. See %s for details. Aborting before install."
FORGE_MSG[en:generating_manifest]="Generating files manifest..."
FORGE_MSG[en:installing_files]="Installing the files on real system"
FORGE_MSG[en:running_finish]="Running post-install steps (finish())..."
FORGE_MSG[en:finish_warning]="finish() reported an error. Check the output above; the package itself is still installed."
FORGE_MSG[en:smithed_success]="Package '%s-%s' smithed successfully!"

# New keys: dependency cascade + extra files (added after Forge went "official")
FORGE_MSG[en:circular_dep]="Circular dependency detected: %s"
FORGE_MSG[en:dep_recipe_not_found]="Recipe for dependency '%s' not found (needed by: %s)"
FORGE_MSG[en:plan_resolving]="Resolving dependencies for %s..."
FORGE_MSG[en:plan_header]="The following packages will also be installed:"
FORGE_MSG[en:plan_count]="%s newly installed."
FORGE_MSG[en:plan_confirm]="Proceed? [Y/n] "
FORGE_MSG[en:plan_aborted]="Aborted."
FORGE_MSG[en:dep_cascade_failed]="Failed to install dependency '%s'. Aborting -- '%s' was not installed."
FORGE_MSG[en:extra_file_header]="Fetching extra files (patches, etc.) for %s..."
FORGE_MSG[en:extra_file_failed]="Failed to fetch an extra file for %s. Aborting before build."
