# Catalogo de mensajes de Forge: Espanol (es)
# Cargado por /usr/bin/forge al iniciar. Rellena FORGE_MSG con claves
# con el prefijo "es:". Las plantillas usan %s/%d de printf, sustituidos
# posicionalmente por la funcion msg() del script principal.

FORGE_MSG[es:smith_usage]="Error: especifica el paquete a smithear, ej: 'forge smith foo'"
FORGE_MSG[es:lock_exists]="Error: ya existe un archivo de bloqueo en /var/lock/forge.lock, probablemente de otra operacion de forge en curso; si no es asi, elimina el archivo de bloqueo e intenta de nuevo."
FORGE_MSG[es:recipe_not_found]="Error: no se encontro la receta de '%s' en %s"
FORGE_MSG[es:dry_run_start]="Comprobando (dry run) el paquete %s..."
FORGE_MSG[es:smith_start]="Smithing el paquete: %s..."
FORGE_MSG[es:checksum_fetch_attempt]="No se encontro checksum local para '%s'; intentando obtenerlo desde CHECKSUM_URL..."
FORGE_MSG[es:missing_deps]="Error: '%s' depende de paquete(s) aun no instalado(s): %s"
FORGE_MSG[es:missing_deps_hint]="Ejecuta 'forge smith <paquete>' para cada uno primero, luego vuelve a intentarlo."
FORGE_MSG[es:dry_run_header]="=== Dry run: forge smith %s ==="
FORGE_MSG[es:dry_run_name]="Nombre: %s"
FORGE_MSG[es:dry_run_version]="Version: %s"
FORGE_MSG[es:dry_run_url]="URL: %s"
FORGE_MSG[es:dry_run_checksum_sha256]="Checksum: SHA256SUM definido, se verificaria"
FORGE_MSG[es:dry_run_checksum_md5]="Checksum: MD5SUM definido, se verificaria"
FORGE_MSG[es:dry_run_checksum_none]="Checksum: ninguno definido, se omitiria la verificacion"
FORGE_MSG[es:dry_run_deps]="Dependencias: %s (todas satisfechas)"
FORGE_MSG[es:dry_run_action_already_installed]="Accion: el paquete ya esta instalado en esta version; una ejecucion real preguntaria si reinstalar (o no haria nada con -y/--yes, forzaria con -f/--force)"
FORGE_MSG[es:dry_run_action_upgrade]="Accion: se actualizaria de %s a %s"
FORGE_MSG[es:dry_run_action_fresh]="Accion: se realizaria una instalacion nueva"
FORGE_MSG[es:dry_run_cached_tarball]="Nota: ya existe un tarball en cache en %s y se reutilizaria si su checksum coincide"
FORGE_MSG[es:dry_run_footer]="No se descargo, compilo ni instalo ningun archivo (dry run)."
FORGE_MSG[es:resume_found]="Se encontro una build incompleta de %s en %s -- retomando donde se quedo."
FORGE_MSG[es:resume_hint]="(usa 'forge smith %s --clean' para descartarla y empezar de nuevo)"
FORGE_MSG[es:archive_unrecognized]="Error: no se reconocio el formato de archivo de '%s' (soportados: .tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip)."
FORGE_MSG[es:interrupted]="¡Interrumpido! El progreso en %s se conservo."
FORGE_MSG[es:interrupted_hint]="Ejecuta 'forge smith %s' de nuevo para continuar donde se quedo, o usa --clean para empezar de cero."
FORGE_MSG[es:already_installed]="El paquete '%s' ya esta instalado en la version %s."
FORGE_MSG[es:forcing_reinstall]="Forzando reinstalacion (-f|--force)."
FORGE_MSG[es:nothing_to_do]="Nada que hacer."
FORGE_MSG[es:prompt_reinstall]="¿Reinstalar de todas formas? [y/N] "
FORGE_MSG[es:reinstall_aborted]="Reinstalacion cancelada."
FORGE_MSG[es:currently_installed_upgrading]="El paquete '%s' esta instalado en la version %s, actualizando a %s."
FORGE_MSG[es:prompt_upgrade]="¿Continuar con la actualizacion a %s? [y/N] "
FORGE_MSG[es:upgrade_aborted]="Actualizacion cancelada."
FORGE_MSG[es:not_installed]="El paquete '%s' no esta instalado actualmente."
FORGE_MSG[es:prompt_smith]="¿Continuar con el smith de '%s' %s? [y/N] "
FORGE_MSG[es:smith_aborted]="Smith cancelado."
FORGE_MSG[es:skip_download_resume]="Omitiendo descarga y extraccion (retomando build existente)."
FORGE_MSG[es:cached_tarball]="Se encontro un tarball valido en cache en %s, omitiendo descarga."
FORGE_MSG[es:downloading]="Get:%s %s"
FORGE_MSG[es:download_failed]="Fallo al descargar %s desde %s"
FORGE_MSG[es:download_empty]="El archivo descargado %s esta ausente o vacio."
FORGE_MSG[es:download_empty_hint]="Revisa tu conexion a internet. Si no es eso, la descarga pudo redirigirse a una pagina de error, o la URL/VERSION en la receta puede ser incorrecta."
FORGE_MSG[es:verifying_checksum]="Verificando checksum (%s)..."
FORGE_MSG[es:checksum_compute_failed]="No se pudo calcular el checksum de %s (archivo ilegible o %s fallo)."
FORGE_MSG[es:checksum_mismatch]="¡El checksum no coincide para %s!"
FORGE_MSG[es:checksum_expected]="	Esperado: %s"
FORGE_MSG[es:checksum_got]="	Obtenido: %s"
FORGE_MSG[es:checksum_kept]="Tarball conservado en %s para inspeccion."
FORGE_MSG[es:checksum_ok]="Checksum OK"
FORGE_MSG[es:no_checksum_warning]="No hay SHA256SUM ni MD5SUM definido en la receta de %s, omitiendo verificacion..."
FORGE_MSG[es:extract_failed]="Fallo al extraer %s"
FORGE_MSG[es:mold_skip]="mold() ya habia terminado en un intento anterior -- saltando directo a smith()."
FORGE_MSG[es:molding]="Haciendo el mold (build)"
FORGE_MSG[es:mold_failed]="mold() fallo para %s. Ver %s para detalles. Abortando antes de instalar."
FORGE_MSG[es:smithing_isolated]="Haciendo el smith en entorno aislado"
FORGE_MSG[es:smith_failed]="smith() fallo para %s. Ver %s para detalles. Abortando antes de instalar."
FORGE_MSG[es:generating_manifest]="Generando manifiesto de archivos..."
FORGE_MSG[es:installing_files]="Instalando los archivos en el sistema real"
FORGE_MSG[es:running_finish]="Ejecutando pasos posteriores a la instalacion (finish())..."
FORGE_MSG[es:finish_warning]="finish() reporto un error. Revisa la salida de arriba; el paquete en si sigue instalado."
FORGE_MSG[es:smithed_success]="¡Paquete '%s-%s' smithed con exito!"

# Claves nuevas: cascada de dependencias + archivos extra
FORGE_MSG[es:circular_dep]="Dependencia circular detectada: %s"
FORGE_MSG[es:dep_recipe_not_found]="No se encontro la receta de la dependencia '%s' (requerida por: %s)"
FORGE_MSG[es:plan_resolving]="Resolviendo dependencias de %s..."
FORGE_MSG[es:plan_header]="Tambien se instalaran los siguientes paquetes:"
FORGE_MSG[es:plan_count]="%s paquete(s) nuevo(s) a instalar."
FORGE_MSG[es:plan_confirm]="¿Continuar? [Y/n] "
FORGE_MSG[es:plan_aborted]="Cancelado."
FORGE_MSG[es:dep_cascade_failed]="Fallo al instalar la dependencia '%s'. Abortando -- '%s' no se instalo."
FORGE_MSG[es:extra_file_header]="Obteniendo archivos extra (parches, etc.) para %s..."
FORGE_MSG[es:extra_file_failed]="Fallo al obtener un archivo extra para %s. Abortando antes de compilar."
