# Catalogo messaggi di Forge: Italiano (it)
# Caricato da /usr/bin/forge all'avvio. Popola FORGE_MSG con chiavi
# con prefisso "it:". I modelli usano %s/%d di printf, sostituiti
# posizionalmente dalla funzione msg() nello script principale.

FORGE_MSG[it:smith_usage]="Error: specifica il pacchetto da smithare, es: 'forge smith foo'"
FORGE_MSG[it:lock_exists]="Error: esiste gia un file di lock in /var/lock/forge.lock, probabilmente di un'altra operazione forge in corso; se non e cosi, rimuovi il file di lock e riprova."
FORGE_MSG[it:recipe_not_found]="Error: ricetta per '%s' non trovata in %s"
FORGE_MSG[it:dry_run_start]="Verifica (dry run) del pacchetto %s..."
FORGE_MSG[it:smith_start]="Smithing del pacchetto: %s..."
FORGE_MSG[it:checksum_fetch_attempt]="Nessun checksum locale trovato per '%s'; tentativo di recupero da CHECKSUM_URL..."
FORGE_MSG[it:missing_deps]="Error: '%s' dipende da pacchetto/i non ancora installato/i: %s"
FORGE_MSG[it:missing_deps_hint]="Esegui prima 'forge smith <pacchetto>' per ciascuno, poi riprova."
FORGE_MSG[it:dry_run_header]="=== Dry run: forge smith %s ==="
FORGE_MSG[it:dry_run_name]="Nome: %s"
FORGE_MSG[it:dry_run_version]="Versione: %s"
FORGE_MSG[it:dry_run_url]="URL: %s"
FORGE_MSG[it:dry_run_checksum_sha256]="Checksum: SHA256SUM definito, verrebbe verificato"
FORGE_MSG[it:dry_run_checksum_md5]="Checksum: MD5SUM definito, verrebbe verificato"
FORGE_MSG[it:dry_run_checksum_none]="Checksum: nessuno definito, la verifica verrebbe saltata"
FORGE_MSG[it:dry_run_deps]="Dipendenze: %s (tutte soddisfatte)"
FORGE_MSG[it:dry_run_action_already_installed]="Azione: il pacchetto e gia installato in questa versione; un'esecuzione reale chiederebbe se reinstallare (o non farebbe nulla con -y/--yes, forzerebbe con -f/--force)"
FORGE_MSG[it:dry_run_action_upgrade]="Azione: aggiornerebbe da %s a %s"
FORGE_MSG[it:dry_run_action_fresh]="Azione: eseguirebbe un'installazione nuova"
FORGE_MSG[it:dry_run_cached_tarball]="Nota: esiste gia un tarball in cache in %s e verrebbe riutilizzato se il checksum corrisponde"
FORGE_MSG[it:dry_run_footer]="Nessun file e stato scaricato, compilato o installato (dry run)."
FORGE_MSG[it:resume_found]="Trovata build incompleta di %s in %s -- ripresa dal punto in cui si era interrotta."
FORGE_MSG[it:resume_hint]="(usa 'forge smith %s --clean' per scartarla e ricominciare da zero)"
FORGE_MSG[it:archive_unrecognized]="Error: formato archivio non riconosciuto per '%s' (supportati: .tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip)."
FORGE_MSG[it:interrupted]="Interrotto! Il progresso in %s e stato mantenuto."
FORGE_MSG[it:interrupted_hint]="Esegui di nuovo 'forge smith %s' per riprendere da dove si era interrotto, oppure usa --clean per ricominciare da zero."
FORGE_MSG[it:already_installed]="Il pacchetto '%s' e gia installato nella versione %s."
FORGE_MSG[it:forcing_reinstall]="Reinstallazione forzata (-f|--force)."
FORGE_MSG[it:nothing_to_do]="Niente da fare."
FORGE_MSG[it:prompt_reinstall]="Reinstallare comunque? [y/N] "
FORGE_MSG[it:reinstall_aborted]="Reinstallazione annullata."
FORGE_MSG[it:currently_installed_upgrading]="Il pacchetto '%s' e attualmente installato nella versione %s, aggiornamento a %s."
FORGE_MSG[it:prompt_upgrade]="Procedere con l'aggiornamento a %s? [y/N] "
FORGE_MSG[it:upgrade_aborted]="Aggiornamento annullato."
FORGE_MSG[it:not_installed]="Il pacchetto '%s' non e attualmente installato."
FORGE_MSG[it:prompt_smith]="Procedere con lo smith di '%s' %s? [y/N] "
FORGE_MSG[it:smith_aborted]="Smith annullato."
FORGE_MSG[it:skip_download_resume]="Download ed estrazione saltati (ripresa di una build esistente)."
FORGE_MSG[it:cached_tarball]="Trovato un tarball valido in cache in %s, download saltato."
FORGE_MSG[it:downloading]="Get:%s %s"
FORGE_MSG[it:download_failed]="Download di %s da %s non riuscito"
FORGE_MSG[it:download_empty]="Il file scaricato %s e mancante o vuoto."
FORGE_MSG[it:download_empty_hint]="Controlla la tua connessione internet. Se non e questo il problema, il download potrebbe essere stato reindirizzato a una pagina di errore, oppure URL/VERSION nella ricetta potrebbero essere sbagliati."
FORGE_MSG[it:verifying_checksum]="Verifica del checksum (%s)..."
FORGE_MSG[it:checksum_compute_failed]="Impossibile calcolare il checksum di %s (file illeggibile o %s non riuscito)."
FORGE_MSG[it:checksum_mismatch]="Checksum non corrispondente per %s!"
FORGE_MSG[it:checksum_expected]="	Atteso: %s"
FORGE_MSG[it:checksum_got]="	Ottenuto: %s"
FORGE_MSG[it:checksum_kept]="Tarball mantenuto in %s per l'ispezione."
FORGE_MSG[it:checksum_ok]="Checksum OK"
FORGE_MSG[it:no_checksum_warning]="Nessun SHA256SUM o MD5SUM definito nella ricetta di %s, verifica saltata..."
FORGE_MSG[it:extract_failed]="Estrazione di %s non riuscita"
FORGE_MSG[it:mold_skip]="mold() era gia terminato in un tentativo precedente -- si passa direttamente a smith()."
FORGE_MSG[it:molding]="Molding (build) in corso"
FORGE_MSG[it:mold_failed]="mold() non riuscito per %s. Vedi %s per i dettagli. Interruzione prima dell'installazione."
FORGE_MSG[it:smithing_isolated]="Smithing in ambiente isolato"
FORGE_MSG[it:smith_failed]="smith() non riuscito per %s. Vedi %s per i dettagli. Interruzione prima dell'installazione."
FORGE_MSG[it:generating_manifest]="Generazione del manifest dei file..."
FORGE_MSG[it:installing_files]="Installazione dei file sul sistema reale"
FORGE_MSG[it:running_finish]="Esecuzione dei passaggi post-installazione (finish())..."
FORGE_MSG[it:finish_warning]="finish() ha segnalato un errore. Controlla l'output sopra; il pacchetto stesso rimane installato."
FORGE_MSG[it:smithed_success]="Pacchetto '%s-%s' smithed con successo!"

# Nuove chiavi: cascata di dipendenze + file extra
FORGE_MSG[it:circular_dep]="Rilevata dipendenza circolare: %s"
FORGE_MSG[it:dep_recipe_not_found]="Ricetta per la dipendenza '%s' non trovata (richiesta da: %s)"
FORGE_MSG[it:plan_resolving]="Risoluzione delle dipendenze di %s..."
FORGE_MSG[it:plan_header]="Verranno installati anche i seguenti pacchetti:"
FORGE_MSG[it:plan_count]="%s nuovo/i pacchetto/i da installare."
FORGE_MSG[it:plan_confirm]="Procedere? [Y/n] "
FORGE_MSG[it:plan_aborted]="Annullato."
FORGE_MSG[it:dep_cascade_failed]="Installazione della dipendenza '%s' non riuscita. Interruzione -- '%s' non e stato installato."
FORGE_MSG[it:extra_file_header]="Recupero dei file extra (patch, ecc.) per %s..."
FORGE_MSG[it:extra_file_failed]="Recupero di un file extra per %s non riuscito. Interruzione prima della build."
