# Catálogo de mensagens do Forge: Português (Brasil) (pt_BR)
# Carregado por /usr/bin/forge na inicialização. Preenche FORGE_MSG com
# chaves prefixadas "pt_BR:". Os textos usam %s/%d do printf,
# substituídos posicionalmente pela função msg() no script principal.

FORGE_MSG[pt_BR:smith_usage]="Error: especifique o pacote a ser smithed, ex: 'forge smith foo'"
FORGE_MSG[pt_BR:lock_exists]="Error: já existe um lock file em /var/lock/forge.lock, provavelmente de uma operação do forge já em andamento; se não houver, remova o lock file e tente de novo."
FORGE_MSG[pt_BR:recipe_not_found]="Error: recipe de '%s' não encontrada em %s"
FORGE_MSG[pt_BR:dry_run_start]="Testando (dry run) o pacote %s..."
FORGE_MSG[pt_BR:smith_start]="Smithing o pacote: %s..."
FORGE_MSG[pt_BR:checksum_fetch_attempt]="Nenhum checksum local encontrado para '%s'; tentando buscar via CHECKSUM_URL..."
FORGE_MSG[pt_BR:missing_deps]="Error: '%s' depende de pacote(s) ainda não instalado(s): %s"
FORGE_MSG[pt_BR:missing_deps_hint]="Rode 'forge smith <pacote>' pra cada um primeiro, depois tente de novo."

FORGE_MSG[pt_BR:dry_run_header]="=== Dry run: forge smith %s ==="
FORGE_MSG[pt_BR:dry_run_name]="Nome: %s"
FORGE_MSG[pt_BR:dry_run_version]="Versão: %s"
FORGE_MSG[pt_BR:dry_run_url]="URL: %s"
FORGE_MSG[pt_BR:dry_run_checksum_sha256]="Checksum: SHA256SUM definido, seria verificado"
FORGE_MSG[pt_BR:dry_run_checksum_md5]="Checksum: MD5SUM definido, seria verificado"
FORGE_MSG[pt_BR:dry_run_checksum_none]="Checksum: nenhum definido, verificação seria pulada"
FORGE_MSG[pt_BR:dry_run_deps]="Dependências: %s (todas satisfeitas)"
FORGE_MSG[pt_BR:dry_run_action_already_installed]="Ação: pacote já instalado nessa versão; uma execução real perguntaria se quer reinstalar (ou não faria nada com -y/--yes, forçaria com -f/--force)"
FORGE_MSG[pt_BR:dry_run_action_upgrade]="Ação: atualizaria de %s para %s"
FORGE_MSG[pt_BR:dry_run_action_fresh]="Ação: faria uma instalação nova"
FORGE_MSG[pt_BR:dry_run_cached_tarball]="Nota: já existe um tarball em cache em %s e seria reaproveitado se o checksum bater"
FORGE_MSG[pt_BR:dry_run_footer]="Nenhum arquivo foi baixado, compilado ou instalado (dry run)."

FORGE_MSG[pt_BR:resume_found]="Build incompleto de %s encontrado em %s -- retomando de onde parou."
FORGE_MSG[pt_BR:resume_hint]="(use 'forge smith %s --clean' para descartar e recomeçar do zero)"
FORGE_MSG[pt_BR:archive_unrecognized]="Error: não reconheci o formato de arquivo de '%s' (suportados: .tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip)."
FORGE_MSG[pt_BR:interrupted]="Interrompido! O progresso em %s foi mantido."
FORGE_MSG[pt_BR:interrupted_hint]="Rode 'forge smith %s' de novo pra retomar de onde parou, ou use --clean pra recomeçar do zero."

FORGE_MSG[pt_BR:already_installed]="O pacote '%s' já está instalado na versão %s."
FORGE_MSG[pt_BR:forcing_reinstall]="Forçando reinstalação (-f|--force)."
FORGE_MSG[pt_BR:nothing_to_do]="Nada a fazer."
FORGE_MSG[pt_BR:prompt_reinstall]="Reinstalar mesmo assim? [y/N] "
FORGE_MSG[pt_BR:reinstall_aborted]="Reinstalação cancelada."
FORGE_MSG[pt_BR:currently_installed_upgrading]="O pacote '%s' está instalado na versão %s, atualizando para %s."
FORGE_MSG[pt_BR:prompt_upgrade]="Prosseguir com a atualização para %s? [y/N] "
FORGE_MSG[pt_BR:upgrade_aborted]="Atualização cancelada."
FORGE_MSG[pt_BR:not_installed]="O pacote '%s' não está instalado no momento."
FORGE_MSG[pt_BR:prompt_smith]="Prosseguir com o smith de '%s' %s? [y/N] "
FORGE_MSG[pt_BR:smith_aborted]="Smith cancelado."

FORGE_MSG[pt_BR:skip_download_resume]="Pulando download e extração (retomando build existente)."
FORGE_MSG[pt_BR:cached_tarball]="Tarball válido encontrado em cache em %s, pulando download."
FORGE_MSG[pt_BR:downloading]="Get:%s %s"
FORGE_MSG[pt_BR:download_failed]="Falha ao baixar %s de %s"
FORGE_MSG[pt_BR:download_empty]="O arquivo baixado %s está ausente ou vazio."
FORGE_MSG[pt_BR:download_empty_hint]="Confira sua conexão com a internet. Se não for isso, o download pode ter sido redirecionado pra uma página de erro, ou a URL/VERSION na recipe pode estar errada."
FORGE_MSG[pt_BR:verifying_checksum]="Verificando checksum (%s)..."
FORGE_MSG[pt_BR:checksum_compute_failed]="Não foi possível calcular o checksum de %s (arquivo ilegível ou %s falhou)."
FORGE_MSG[pt_BR:checksum_mismatch]="Checksum não bate para %s!"
FORGE_MSG[pt_BR:checksum_expected]="	Esperado: %s"
FORGE_MSG[pt_BR:checksum_got]="	Obtido:   %s"
FORGE_MSG[pt_BR:checksum_kept]="Tarball mantido em %s para inspeção."
FORGE_MSG[pt_BR:checksum_ok]="Checksum OK"
FORGE_MSG[pt_BR:no_checksum_warning]="Nenhum SHA256SUM ou MD5SUM definido na recipe de %s, pulando verificação..."
FORGE_MSG[pt_BR:extract_failed]="Falha ao extrair %s"

FORGE_MSG[pt_BR:mold_skip]="mold() já havia terminado numa tentativa anterior -- pulando direto pro smith()."
FORGE_MSG[pt_BR:molding]="Fazendo o mold (build)"
FORGE_MSG[pt_BR:mold_failed]="mold() falhou para %s. Veja %s para detalhes. Abortando antes de instalar."
FORGE_MSG[pt_BR:smithing_isolated]="Fazendo o smith em ambiente isolado"
FORGE_MSG[pt_BR:smith_failed]="smith() falhou para %s. Veja %s para detalhes. Abortando antes de instalar."
FORGE_MSG[pt_BR:generating_manifest]="Gerando manifesto de arquivos..."
FORGE_MSG[pt_BR:installing_files]="Instalando os arquivos no sistema real"
FORGE_MSG[pt_BR:running_finish]="Rodando passos pós-instalação (finish())..."
FORGE_MSG[pt_BR:finish_warning]="finish() reportou um erro. Confira a saída acima; o pacote em si ainda está instalado."
FORGE_MSG[pt_BR:smithed_success]="Pacote '%s-%s' smithed com sucesso!"

# Chaves novas: cascata de dependências + arquivos extras (depois do Forge virar "oficial")
FORGE_MSG[pt_BR:circular_dep]="Dependência circular detectada: %s"
FORGE_MSG[pt_BR:dep_recipe_not_found]="Recipe da dependência '%s' não encontrada (necessária por: %s)"
FORGE_MSG[pt_BR:plan_resolving]="Resolvendo dependências de %s..."
FORGE_MSG[pt_BR:plan_header]="Os seguintes pacotes também serão instalados:"
FORGE_MSG[pt_BR:plan_count]="%s novo(s) pacote(s) a instalar."
FORGE_MSG[pt_BR:plan_confirm]="Continuar? [Y/n] "
FORGE_MSG[pt_BR:plan_aborted]="Cancelado."
FORGE_MSG[pt_BR:dep_cascade_failed]="Falha ao instalar a dependência '%s'. Abortando -- '%s' não foi instalado."
FORGE_MSG[pt_BR:extra_file_header]="Baixando arquivos extras (patches, etc.) de %s..."
FORGE_MSG[pt_BR:extra_file_failed]="Falha ao baixar um arquivo extra de %s. Abortando antes do build."
