# Forge 消息目录：简体中文 (zh_CN)
# 由 /usr/bin/forge 在启动时加载，用前缀为 "zh_CN:" 的键填充 FORGE_MSG。
# 模板使用 printf 的 %s/%d 占位符，由主脚本中的 msg() 函数按位置替换。

FORGE_MSG[zh_CN:smith_usage]="错误：请指定要 smith 的软件包，例如：'forge smith foo'"
FORGE_MSG[zh_CN:lock_exists]="错误：/var/lock/forge.lock 锁文件已存在，可能有另一个 forge 操作正在进行；如果不是，请删除锁文件后重试。"
FORGE_MSG[zh_CN:recipe_not_found]="错误：在 %s 中未找到 '%s' 的配方（recipe）"
FORGE_MSG[zh_CN:dry_run_start]="正在检查（dry run）软件包 %s..."
FORGE_MSG[zh_CN:smith_start]="正在 smith 软件包：%s..."
FORGE_MSG[zh_CN:checksum_fetch_attempt]="未找到 '%s' 的本地校验和；正在尝试从 CHECKSUM_URL 获取..."
FORGE_MSG[zh_CN:missing_deps]="错误：'%s' 依赖尚未安装的软件包：%s"
FORGE_MSG[zh_CN:missing_deps_hint]="请先为每一个依赖执行 'forge smith <软件包>'，然后重试。"
FORGE_MSG[zh_CN:dry_run_header]="=== Dry run：forge smith %s ==="
FORGE_MSG[zh_CN:dry_run_name]="名称：%s"
FORGE_MSG[zh_CN:dry_run_version]="版本：%s"
FORGE_MSG[zh_CN:dry_run_url]="URL：%s"
FORGE_MSG[zh_CN:dry_run_checksum_sha256]="校验和：已定义 SHA256SUM，将会被验证"
FORGE_MSG[zh_CN:dry_run_checksum_md5]="校验和：已定义 MD5SUM，将会被验证"
FORGE_MSG[zh_CN:dry_run_checksum_none]="校验和：未定义，验证将被跳过"
FORGE_MSG[zh_CN:dry_run_deps]="依赖：%s（全部满足）"
FORGE_MSG[zh_CN:dry_run_action_already_installed]="操作：该版本的软件包已安装；实际执行会询问是否重新安装（使用 -y/--yes 则不做任何操作，使用 -f/--force 则强制执行）"
FORGE_MSG[zh_CN:dry_run_action_upgrade]="操作：将从 %s 升级到 %s"
FORGE_MSG[zh_CN:dry_run_action_fresh]="操作：将执行全新安装"
FORGE_MSG[zh_CN:dry_run_cached_tarball]="提示：%s 已存在缓存的压缩包，如果校验和匹配将会被重用"
FORGE_MSG[zh_CN:dry_run_footer]="未下载、编译或安装任何文件（dry run）。"
FORGE_MSG[zh_CN:resume_found]="在 %s 发现 %s 的未完成构建 -- 将从中断处继续。"
FORGE_MSG[zh_CN:resume_hint]="（使用 'forge smith %s --clean' 可放弃并重新开始）"
FORGE_MSG[zh_CN:archive_unrecognized]="错误：无法识别 '%s' 的压缩包格式（支持：.tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip）。"
FORGE_MSG[zh_CN:interrupted]="已中断！%s 中的进度已保留。"
FORGE_MSG[zh_CN:interrupted_hint]="再次运行 'forge smith %s' 可从中断处继续，或使用 --clean 重新开始。"
FORGE_MSG[zh_CN:already_installed]="软件包 '%s' 已安装版本 %s。"
FORGE_MSG[zh_CN:forcing_reinstall]="强制重新安装（-f|--force）。"
FORGE_MSG[zh_CN:nothing_to_do]="无需操作。"
FORGE_MSG[zh_CN:prompt_reinstall]="仍要重新安装吗？[y/N] "
FORGE_MSG[zh_CN:reinstall_aborted]="重新安装已取消。"
FORGE_MSG[zh_CN:currently_installed_upgrading]="软件包 '%s' 当前安装版本为 %s，正在升级到 %s。"
FORGE_MSG[zh_CN:prompt_upgrade]="是否继续升级到 %s？[y/N] "
FORGE_MSG[zh_CN:upgrade_aborted]="升级已取消。"
FORGE_MSG[zh_CN:not_installed]="软件包 '%s' 当前未安装。"
FORGE_MSG[zh_CN:prompt_smith]="是否继续 smith '%s' %s？[y/N] "
FORGE_MSG[zh_CN:smith_aborted]="Smith 已取消。"
FORGE_MSG[zh_CN:skip_download_resume]="跳过下载和解压（继续已有的构建）。"
FORGE_MSG[zh_CN:cached_tarball]="在 %s 发现有效的缓存压缩包，跳过下载。"
FORGE_MSG[zh_CN:downloading]="Get:%s %s"
FORGE_MSG[zh_CN:download_failed]="从 %s 下载 %s 失败"
FORGE_MSG[zh_CN:download_empty]="下载的文件 %s 缺失或为空。"
FORGE_MSG[zh_CN:download_empty_hint]="请检查你的网络连接。如果不是这个问题，下载可能被重定向到了错误页面，或者配方中的 URL/VERSION 可能有误。"
FORGE_MSG[zh_CN:verifying_checksum]="正在验证校验和（%s）..."
FORGE_MSG[zh_CN:checksum_compute_failed]="无法计算 %s 的校验和（文件不可读或 %s 执行失败）。"
FORGE_MSG[zh_CN:checksum_mismatch]="%s 的校验和不匹配！"
FORGE_MSG[zh_CN:checksum_expected]="	期望值：%s"
FORGE_MSG[zh_CN:checksum_got]="	实际值：%s"
FORGE_MSG[zh_CN:checksum_kept]="压缩包已保留在 %s 以供检查。"
FORGE_MSG[zh_CN:checksum_ok]="校验和正确"
FORGE_MSG[zh_CN:no_checksum_warning]="%s 的配方中未定义 SHA256SUM 或 MD5SUM，跳过验证..."
FORGE_MSG[zh_CN:extract_failed]="解压 %s 失败"
FORGE_MSG[zh_CN:mold_skip]="mold() 在之前的尝试中已经完成 -- 直接跳到 smith()。"
FORGE_MSG[zh_CN:molding]="正在执行 mold（构建）"
FORGE_MSG[zh_CN:mold_failed]="%s 的 mold() 失败。详情请查看 %s。安装前中止。"
FORGE_MSG[zh_CN:smithing_isolated]="正在隔离环境中执行 smith"
FORGE_MSG[zh_CN:smith_failed]="%s 的 smith() 失败。详情请查看 %s。安装前中止。"
FORGE_MSG[zh_CN:generating_manifest]="正在生成文件清单..."
FORGE_MSG[zh_CN:installing_files]="正在将文件安装到实际系统"
FORGE_MSG[zh_CN:running_finish]="正在执行安装后步骤（finish())..."
FORGE_MSG[zh_CN:finish_warning]="finish() 报告了一个错误。请查看上方输出；软件包本身仍已安装。"
FORGE_MSG[zh_CN:smithed_success]="软件包 '%s-%s' smithed 成功！"

# 新增键：依赖级联安装 + 额外文件
FORGE_MSG[zh_CN:circular_dep]="检测到循环依赖：%s"
FORGE_MSG[zh_CN:dep_recipe_not_found]="未找到依赖 '%s' 的配方（被 %s 需要）"
FORGE_MSG[zh_CN:plan_resolving]="正在解析 %s 的依赖关系..."
FORGE_MSG[zh_CN:plan_header]="还将安装以下软件包："
FORGE_MSG[zh_CN:plan_count]="将新安装 %s 个软件包。"
FORGE_MSG[zh_CN:plan_confirm]="是否继续？[Y/n] "
FORGE_MSG[zh_CN:plan_aborted]="已取消。"
FORGE_MSG[zh_CN:dep_cascade_failed]="依赖 '%s' 安装失败。正在中止 -- '%s' 未被安装。"
FORGE_MSG[zh_CN:extra_file_header]="正在获取 %s 的额外文件（补丁等）..."
FORGE_MSG[zh_CN:extra_file_failed]="获取 %s 的额外文件失败。构建前中止。"
