# Catalogue de messages Forge : Francais (fr)
# Charge par /usr/bin/forge au demarrage. Remplit FORGE_MSG avec des
# cles prefixees "fr:". Les modeles utilisent %s/%d de printf, substitues
# positionnellement par la fonction msg() du script principal.

FORGE_MSG[fr:smith_usage]="Error : indiquez le paquet a smither, ex : 'forge smith foo'"
FORGE_MSG[fr:lock_exists]="Error : un fichier de verrou existe deja dans /var/lock/forge.lock, probablement une autre operation forge en cours ; sinon, supprimez le fichier de verrou et reessayez."
FORGE_MSG[fr:recipe_not_found]="Error : recette introuvable pour '%s' dans %s"
FORGE_MSG[fr:dry_run_start]="Verification (dry run) du paquet %s..."
FORGE_MSG[fr:smith_start]="Smithing du paquet : %s..."
FORGE_MSG[fr:checksum_fetch_attempt]="Aucun checksum local trouve pour '%s' ; tentative de recuperation via CHECKSUM_URL..."
FORGE_MSG[fr:missing_deps]="Error : '%s' depend de paquet(s) non installe(s) : %s"
FORGE_MSG[fr:missing_deps_hint]="Lancez 'forge smith <paquet>' pour chacun d'abord, puis reessayez."
FORGE_MSG[fr:dry_run_header]="=== Dry run : forge smith %s ==="
FORGE_MSG[fr:dry_run_name]="Nom : %s"
FORGE_MSG[fr:dry_run_version]="Version : %s"
FORGE_MSG[fr:dry_run_url]="URL : %s"
FORGE_MSG[fr:dry_run_checksum_sha256]="Checksum : SHA256SUM defini, serait verifie"
FORGE_MSG[fr:dry_run_checksum_md5]="Checksum : MD5SUM defini, serait verifie"
FORGE_MSG[fr:dry_run_checksum_none]="Checksum : aucun defini, la verification serait ignoree"
FORGE_MSG[fr:dry_run_deps]="Dependances : %s (toutes satisfaites)"
FORGE_MSG[fr:dry_run_action_already_installed]="Action : le paquet est deja installe dans cette version ; une execution reelle demanderait de reinstaller (ou ne ferait rien avec -y/--yes, forcerait avec -f/--force)"
FORGE_MSG[fr:dry_run_action_upgrade]="Action : mettrait a niveau de %s vers %s"
FORGE_MSG[fr:dry_run_action_fresh]="Action : effectuerait une nouvelle installation"
FORGE_MSG[fr:dry_run_cached_tarball]="Note : une archive en cache existe deja a %s et serait reutilisee si son checksum correspond"
FORGE_MSG[fr:dry_run_footer]="Aucun fichier n'a ete telecharge, compile ou installe (dry run)."
FORGE_MSG[fr:resume_found]="Build incomplet de %s trouve dans %s -- reprise a l'endroit ou il s'est arrete."
FORGE_MSG[fr:resume_hint]="(utilisez 'forge smith %s --clean' pour l'abandonner et recommencer a zero)"
FORGE_MSG[fr:archive_unrecognized]="Error : format d'archive non reconnu pour '%s' (supportes : .tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip)."
FORGE_MSG[fr:interrupted]="Interrompu ! La progression dans %s a ete conservee."
FORGE_MSG[fr:interrupted_hint]="Relancez 'forge smith %s' pour reprendre ou vous en etiez, ou utilisez --clean pour recommencer a zero."
FORGE_MSG[fr:already_installed]="Le paquet '%s' est deja installe en version %s."
FORGE_MSG[fr:forcing_reinstall]="Reinstallation forcee (-f|--force)."
FORGE_MSG[fr:nothing_to_do]="Rien a faire."
FORGE_MSG[fr:prompt_reinstall]="Reinstaller quand meme ? [y/N] "
FORGE_MSG[fr:reinstall_aborted]="Reinstallation annulee."
FORGE_MSG[fr:currently_installed_upgrading]="Le paquet '%s' est installe en version %s, mise a niveau vers %s."
FORGE_MSG[fr:prompt_upgrade]="Continuer la mise a niveau vers %s ? [y/N] "
FORGE_MSG[fr:upgrade_aborted]="Mise a niveau annulee."
FORGE_MSG[fr:not_installed]="Le paquet '%s' n'est pas installe actuellement."
FORGE_MSG[fr:prompt_smith]="Continuer le smith de '%s' %s ? [y/N] "
FORGE_MSG[fr:smith_aborted]="Smith annule."
FORGE_MSG[fr:skip_download_resume]="Telechargement et extraction ignores (reprise d'un build existant)."
FORGE_MSG[fr:cached_tarball]="Archive valide trouvee en cache a %s, telechargement ignore."
FORGE_MSG[fr:downloading]="Get:%s %s"
FORGE_MSG[fr:download_failed]="Echec du telechargement de %s depuis %s"
FORGE_MSG[fr:download_empty]="Le fichier telecharge %s est manquant ou vide."
FORGE_MSG[fr:download_empty_hint]="Verifiez votre connexion internet. Si ce n'est pas le probleme, le telechargement a peut-etre ete redirige vers une page d'erreur, ou l'URL/VERSION de la recette est peut-etre incorrecte."
FORGE_MSG[fr:verifying_checksum]="Verification du checksum (%s)..."
FORGE_MSG[fr:checksum_compute_failed]="Impossible de calculer le checksum de %s (fichier illisible ou %s a echoue)."
FORGE_MSG[fr:checksum_mismatch]="Checksum incorrect pour %s !"
FORGE_MSG[fr:checksum_expected]="	Attendu : %s"
FORGE_MSG[fr:checksum_got]="	Obtenu :  %s"
FORGE_MSG[fr:checksum_kept]="Archive conservee a %s pour inspection."
FORGE_MSG[fr:checksum_ok]="Checksum OK"
FORGE_MSG[fr:no_checksum_warning]="Aucun SHA256SUM ni MD5SUM defini dans la recette de %s, verification ignoree..."
FORGE_MSG[fr:extract_failed]="Echec de l'extraction de %s"
FORGE_MSG[fr:mold_skip]="mold() avait deja termine lors d'une tentative precedente -- passage direct a smith()."
FORGE_MSG[fr:molding]="Molding (build) en cours"
FORGE_MSG[fr:mold_failed]="mold() a echoue pour %s. Voir %s pour les details. Abandon avant l'installation."
FORGE_MSG[fr:smithing_isolated]="Smithing dans un environnement isole"
FORGE_MSG[fr:smith_failed]="smith() a echoue pour %s. Voir %s pour les details. Abandon avant l'installation."
FORGE_MSG[fr:generating_manifest]="Generation du manifeste de fichiers..."
FORGE_MSG[fr:installing_files]="Installation des fichiers sur le systeme reel"
FORGE_MSG[fr:running_finish]="Execution des etapes post-installation (finish())..."
FORGE_MSG[fr:finish_warning]="finish() a signale une erreur. Consultez la sortie ci-dessus ; le paquet lui-meme reste installe."
FORGE_MSG[fr:smithed_success]="Paquet '%s-%s' smithed avec succes !"

# Nouvelles cles : cascade de dependances + fichiers supplementaires
FORGE_MSG[fr:circular_dep]="Dependance circulaire detectee : %s"
FORGE_MSG[fr:dep_recipe_not_found]="Recette introuvable pour la dependance '%s' (requise par : %s)"
FORGE_MSG[fr:plan_resolving]="Resolution des dependances de %s..."
FORGE_MSG[fr:plan_header]="Les paquets suivants seront aussi installes :"
FORGE_MSG[fr:plan_count]="%s nouveau(x) paquet(s) a installer."
FORGE_MSG[fr:plan_confirm]="Continuer ? [Y/n] "
FORGE_MSG[fr:plan_aborted]="Annule."
FORGE_MSG[fr:dep_cascade_failed]="Echec de l'installation de la dependance '%s'. Abandon -- '%s' n'a pas ete installe."
FORGE_MSG[fr:extra_file_header]="Recuperation des fichiers supplementaires (patchs, etc.) pour %s..."
FORGE_MSG[fr:extra_file_failed]="Echec de la recuperation d'un fichier supplementaire pour %s. Abandon avant la compilation."
