# Forge メッセージカタログ: 日本語 (ja)
# /usr/bin/forge の起動時に読み込まれます。"ja:" を接頭辞とするキーで
# FORGE_MSG を埋めます。テンプレートは printf の %s/%d を使用し、
# メインスクリプトの msg() 関数によって位置ごとに置換されます。

FORGE_MSG[ja:smith_usage]="エラー: smith するパッケージを指定してください。例: 'forge smith foo'"
FORGE_MSG[ja:lock_exists]="エラー: /var/lock/forge.lock にロックファイルが既に存在します。別の forge 操作が実行中の可能性があります。そうでない場合はロックファイルを削除して再試行してください。"
FORGE_MSG[ja:recipe_not_found]="エラー: %s に '%s' のレシピが見つかりません"
FORGE_MSG[ja:dry_run_start]="パッケージ %s を確認中（dry run）..."
FORGE_MSG[ja:smith_start]="パッケージを smithing 中: %s..."
FORGE_MSG[ja:checksum_fetch_attempt]="'%s' のローカルチェックサムが見つかりません。CHECKSUM_URL から取得を試みます..."
FORGE_MSG[ja:missing_deps]="エラー: '%s' は未インストールのパッケージに依存しています: %s"
FORGE_MSG[ja:missing_deps_hint]="先にそれぞれに対して 'forge smith <パッケージ>' を実行してから、再試行してください。"
FORGE_MSG[ja:dry_run_header]="=== Dry run: forge smith %s ==="
FORGE_MSG[ja:dry_run_name]="名前: %s"
FORGE_MSG[ja:dry_run_version]="バージョン: %s"
FORGE_MSG[ja:dry_run_url]="URL: %s"
FORGE_MSG[ja:dry_run_checksum_sha256]="チェックサム: SHA256SUM が定義されています。検証されます"
FORGE_MSG[ja:dry_run_checksum_md5]="チェックサム: MD5SUM が定義されています。検証されます"
FORGE_MSG[ja:dry_run_checksum_none]="チェックサム: 未定義のため、検証はスキップされます"
FORGE_MSG[ja:dry_run_deps]="依存関係: %s（すべて満たされています）"
FORGE_MSG[ja:dry_run_action_already_installed]="動作: このバージョンのパッケージは既にインストールされています。実際の実行では再インストールするか確認します（-y/--yes では何もせず、-f/--force では強制実行）"
FORGE_MSG[ja:dry_run_action_upgrade]="動作: %s から %s へアップグレードします"
FORGE_MSG[ja:dry_run_action_fresh]="動作: 新規インストールを実行します"
FORGE_MSG[ja:dry_run_cached_tarball]="注記: %s にキャッシュ済みのアーカイブが既に存在し、チェックサムが一致すれば再利用されます"
FORGE_MSG[ja:dry_run_footer]="ファイルのダウンロード、ビルド、インストールは行われませんでした（dry run）。"
FORGE_MSG[ja:resume_found]="%s の未完了のビルドが %s に見つかりました -- 中断した箇所から再開します。"
FORGE_MSG[ja:resume_hint]="（破棄して最初からやり直すには 'forge smith %s --clean' を使用してください）"
FORGE_MSG[ja:archive_unrecognized]="エラー: '%s' のアーカイブ形式を認識できませんでした（対応形式: .tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip）。"
FORGE_MSG[ja:interrupted]="中断されました！%s の進捗は保持されています。"
FORGE_MSG[ja:interrupted_hint]="'forge smith %s' を再度実行すると中断箇所から再開します。最初からやり直すには --clean を使用してください。"
FORGE_MSG[ja:already_installed]="パッケージ '%s' は既にバージョン %s がインストールされています。"
FORGE_MSG[ja:forcing_reinstall]="再インストールを強制しています（-f|--force）。"
FORGE_MSG[ja:nothing_to_do]="何もすることはありません。"
FORGE_MSG[ja:prompt_reinstall]="それでも再インストールしますか？ [y/N] "
FORGE_MSG[ja:reinstall_aborted]="再インストールを中止しました。"
FORGE_MSG[ja:currently_installed_upgrading]="パッケージ '%s' は現在バージョン %s がインストールされています。%s へアップグレードします。"
FORGE_MSG[ja:prompt_upgrade]="%s へのアップグレードを続行しますか？ [y/N] "
FORGE_MSG[ja:upgrade_aborted]="アップグレードを中止しました。"
FORGE_MSG[ja:not_installed]="パッケージ '%s' は現在インストールされていません。"
FORGE_MSG[ja:prompt_smith]="'%s' %s の smith を続行しますか？ [y/N] "
FORGE_MSG[ja:smith_aborted]="Smith を中止しました。"
FORGE_MSG[ja:skip_download_resume]="ダウンロードと展開をスキップします（既存のビルドを再開）。"
FORGE_MSG[ja:cached_tarball]="%s に有効なキャッシュ済みアーカイブが見つかりました。ダウンロードをスキップします。"
FORGE_MSG[ja:downloading]="Get:%s %s"
FORGE_MSG[ja:download_failed]="%s から %s のダウンロードに失敗しました"
FORGE_MSG[ja:download_empty]="ダウンロードされたファイル %s が存在しないか、空です。"
FORGE_MSG[ja:download_empty_hint]="インターネット接続を確認してください。問題がなければ、ダウンロードがエラーページにリダイレクトされたか、レシピ内の URL/VERSION が間違っている可能性があります。"
FORGE_MSG[ja:verifying_checksum]="チェックサムを検証中（%s）..."
FORGE_MSG[ja:checksum_compute_failed]="%s のチェックサムを計算できませんでした（ファイルが読み取れないか、%s が失敗しました）。"
FORGE_MSG[ja:checksum_mismatch]="%s のチェックサムが一致しません！"
FORGE_MSG[ja:checksum_expected]="	期待値: %s"
FORGE_MSG[ja:checksum_got]="	実際値: %s"
FORGE_MSG[ja:checksum_kept]="確認のためアーカイブを %s に保持しました。"
FORGE_MSG[ja:checksum_ok]="チェックサム OK"
FORGE_MSG[ja:no_checksum_warning]="%s のレシピに SHA256SUM も MD5SUM も定義されていません。検証をスキップします..."
FORGE_MSG[ja:extract_failed]="%s の展開に失敗しました"
FORGE_MSG[ja:mold_skip]="mold() は前回の試行で既に完了しています -- smith() に直接進みます。"
FORGE_MSG[ja:molding]="Molding（ビルド）中"
FORGE_MSG[ja:mold_failed]="%s の mold() が失敗しました。詳細は %s を参照してください。インストール前に中止します。"
FORGE_MSG[ja:smithing_isolated]="分離環境で smithing 中"
FORGE_MSG[ja:smith_failed]="%s の smith() が失敗しました。詳細は %s を参照してください。インストール前に中止します。"
FORGE_MSG[ja:generating_manifest]="ファイルマニフェストを生成中..."
FORGE_MSG[ja:installing_files]="実際のシステムにファイルをインストール中"
FORGE_MSG[ja:running_finish]="インストール後の手順を実行中（finish())..."
FORGE_MSG[ja:finish_warning]="finish() がエラーを報告しました。上記の出力を確認してください。パッケージ自体はインストールされたままです。"
FORGE_MSG[ja:smithed_success]="パッケージ '%s-%s' の smith に成功しました！"

# 新しいキー: 依存関係のカスケードインストール + 追加ファイル
FORGE_MSG[ja:circular_dep]="循環依存が検出されました: %s"
FORGE_MSG[ja:dep_recipe_not_found]="依存関係 '%s' のレシピが見つかりません（%s に必要とされています）"
FORGE_MSG[ja:plan_resolving]="%s の依存関係を解決中..."
FORGE_MSG[ja:plan_header]="以下のパッケージも同時にインストールされます:"
FORGE_MSG[ja:plan_count]="新たにインストールされるパッケージ: %s 個。"
FORGE_MSG[ja:plan_confirm]="続行しますか？ [Y/n] "
FORGE_MSG[ja:plan_aborted]="中止しました。"
FORGE_MSG[ja:dep_cascade_failed]="依存関係 '%s' のインストールに失敗しました。中止します -- '%s' はインストールされませんでした。"
FORGE_MSG[ja:extra_file_header]="%s の追加ファイル（パッチなど）を取得中..."
FORGE_MSG[ja:extra_file_failed]="%s の追加ファイルの取得に失敗しました。ビルド前に中止します。"
