# Каталог сообщений Forge: Русский (ru)
# Загружается /usr/bin/forge при запуске. Заполняет FORGE_MSG ключами
# с префиксом "ru:". Шаблоны используют %s/%d из printf, подставляемые
# позиционно функцией msg() в основном скрипте.

FORGE_MSG[ru:smith_usage]="Error: укажите пакет для smith, напр.: 'forge smith foo'"
FORGE_MSG[ru:lock_exists]="Error: уже существует файл блокировки /var/lock/forge.lock, вероятно от другой выполняющейся операции forge; если это не так, удалите файл блокировки и попробуйте снова."
FORGE_MSG[ru:recipe_not_found]="Error: рецепт для '%s' не найден в %s"
FORGE_MSG[ru:dry_run_start]="Проверка (dry run) пакета %s..."
FORGE_MSG[ru:smith_start]="Smithing пакета: %s..."
FORGE_MSG[ru:checksum_fetch_attempt]="Локальная контрольная сумма для '%s' не найдена; попытка получить её из CHECKSUM_URL..."
FORGE_MSG[ru:missing_deps]="Error: '%s' зависит от ещё не установленных пакетов: %s"
FORGE_MSG[ru:missing_deps_hint]="Сначала выполните 'forge smith <пакет>' для каждого из них, затем повторите попытку."
FORGE_MSG[ru:dry_run_header]="=== Dry run: forge smith %s ==="
FORGE_MSG[ru:dry_run_name]="Имя: %s"
FORGE_MSG[ru:dry_run_version]="Версия: %s"
FORGE_MSG[ru:dry_run_url]="URL: %s"
FORGE_MSG[ru:dry_run_checksum_sha256]="Контрольная сумма: задан SHA256SUM, будет проверен"
FORGE_MSG[ru:dry_run_checksum_md5]="Контрольная сумма: задан MD5SUM, будет проверен"
FORGE_MSG[ru:dry_run_checksum_none]="Контрольная сумма: не задана, проверка будет пропущена"
FORGE_MSG[ru:dry_run_deps]="Зависимости: %s (все удовлетворены)"
FORGE_MSG[ru:dry_run_action_already_installed]="Действие: пакет уже установлен в этой версии; при реальном запуске будет предложено переустановить (или ничего не делать с -y/--yes, принудительно с -f/--force)"
FORGE_MSG[ru:dry_run_action_upgrade]="Действие: обновление с %s до %s"
FORGE_MSG[ru:dry_run_action_fresh]="Действие: будет выполнена новая установка"
FORGE_MSG[ru:dry_run_cached_tarball]="Примечание: в кэше уже есть архив %s, он будет использован повторно, если совпадёт контрольная сумма"
FORGE_MSG[ru:dry_run_footer]="Файлы не были загружены, собраны или установлены (dry run)."
FORGE_MSG[ru:resume_found]="Найдена незавершённая сборка %s в %s -- продолжение с того места, где остановились."
FORGE_MSG[ru:resume_hint]="(используйте 'forge smith %s --clean', чтобы отбросить её и начать заново)"
FORGE_MSG[ru:archive_unrecognized]="Error: не удалось распознать формат архива '%s' (поддерживаются: .tar.gz/.tgz/.tar.xz/.tar.bz2/.tar.zst/.tar/.zip)."
FORGE_MSG[ru:interrupted]="Прервано! Прогресс в %s сохранён."
FORGE_MSG[ru:interrupted_hint]="Запустите 'forge smith %s' снова, чтобы продолжить с того места, или используйте --clean, чтобы начать заново."
FORGE_MSG[ru:already_installed]="Пакет '%s' уже установлен в версии %s."
FORGE_MSG[ru:forcing_reinstall]="Принудительная переустановка (-f|--force)."
FORGE_MSG[ru:nothing_to_do]="Нечего делать."
FORGE_MSG[ru:prompt_reinstall]="Всё равно переустановить? [y/N] "
FORGE_MSG[ru:reinstall_aborted]="Переустановка отменена."
FORGE_MSG[ru:currently_installed_upgrading]="Пакет '%s' сейчас установлен в версии %s, обновление до %s."
FORGE_MSG[ru:prompt_upgrade]="Продолжить обновление до %s? [y/N] "
FORGE_MSG[ru:upgrade_aborted]="Обновление отменено."
FORGE_MSG[ru:not_installed]="Пакет '%s' сейчас не установлен."
FORGE_MSG[ru:prompt_smith]="Продолжить smith '%s' %s? [y/N] "
FORGE_MSG[ru:smith_aborted]="Smith отменён."
FORGE_MSG[ru:skip_download_resume]="Загрузка и распаковка пропущены (продолжение существующей сборки)."
FORGE_MSG[ru:cached_tarball]="Найден действительный архив в кэше %s, загрузка пропущена."
FORGE_MSG[ru:downloading]="Get:%s %s"
FORGE_MSG[ru:download_failed]="Не удалось загрузить %s из %s"
FORGE_MSG[ru:download_empty]="Загруженный файл %s отсутствует или пуст."
FORGE_MSG[ru:download_empty_hint]="Проверьте подключение к интернету. Если дело не в этом, возможно, загрузка была перенаправлена на страницу с ошибкой, либо URL/VERSION в рецепте указаны неверно."
FORGE_MSG[ru:verifying_checksum]="Проверка контрольной суммы (%s)..."
FORGE_MSG[ru:checksum_compute_failed]="Не удалось вычислить контрольную сумму для %s (файл нечитаем или %s завершился с ошибкой)."
FORGE_MSG[ru:checksum_mismatch]="Контрольная сумма не совпадает для %s!"
FORGE_MSG[ru:checksum_expected]="	Ожидалось: %s"
FORGE_MSG[ru:checksum_got]="	Получено: %s"
FORGE_MSG[ru:checksum_kept]="Архив сохранён в %s для проверки."
FORGE_MSG[ru:checksum_ok]="Контрольная сумма верна"
FORGE_MSG[ru:no_checksum_warning]="В рецепте для %s не задан ни SHA256SUM, ни MD5SUM, проверка пропущена..."
FORGE_MSG[ru:extract_failed]="Не удалось распаковать %s"
FORGE_MSG[ru:mold_skip]="mold() уже завершился при предыдущей попытке -- переход сразу к smith()."
FORGE_MSG[ru:molding]="Выполняется mold (сборка)"
FORGE_MSG[ru:mold_failed]="mold() завершился с ошибкой для %s. Подробности см. в %s. Прерывание перед установкой."
FORGE_MSG[ru:smithing_isolated]="Smithing в изолированном окружении"
FORGE_MSG[ru:smith_failed]="smith() завершился с ошибкой для %s. Подробности см. в %s. Прерывание перед установкой."
FORGE_MSG[ru:generating_manifest]="Создание манифеста файлов..."
FORGE_MSG[ru:installing_files]="Установка файлов в реальную систему"
FORGE_MSG[ru:running_finish]="Выполнение шагов после установки (finish())..."
FORGE_MSG[ru:finish_warning]="finish() сообщил об ошибке. Проверьте вывод выше; сам пакет остаётся установленным."
FORGE_MSG[ru:smithed_success]="Пакет '%s-%s' успешно smithed!"

# Новые ключи: каскад зависимостей + дополнительные файлы
FORGE_MSG[ru:circular_dep]="Обнаружена циклическая зависимость: %s"
FORGE_MSG[ru:dep_recipe_not_found]="Рецепт для зависимости '%s' не найден (требуется для: %s)"
FORGE_MSG[ru:plan_resolving]="Разрешение зависимостей для %s..."
FORGE_MSG[ru:plan_header]="Также будут установлены следующие пакеты:"
FORGE_MSG[ru:plan_count]="Новых пакетов к установке: %s."
FORGE_MSG[ru:plan_confirm]="Продолжить? [Y/n] "
FORGE_MSG[ru:plan_aborted]="Отменено."
FORGE_MSG[ru:dep_cascade_failed]="Не удалось установить зависимость '%s'. Прерывание -- '%s' не был установлен."
FORGE_MSG[ru:extra_file_header]="Загрузка дополнительных файлов (патчи и т.д.) для %s..."
FORGE_MSG[ru:extra_file_failed]="Не удалось загрузить дополнительный файл для %s. Прерывание перед сборкой."
